In [31]:
import pandas as pd
import numpy as np

**Загрузить данные из CSV-файла в датафрейм с помощью библиотеки Pandas, отобразить первые 10 и последние 10 строк**

In [32]:
from google.colab import files
uploaded = files.upload()

Saving dataset.csv to dataset (1).csv


In [33]:
data = pd.read_csv('dataset.csv', sep = ",")

In [34]:
data.head(10)

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
5  0.132786  0.079557  0.119090  0.067958  0.209592  0.141634   1.932562   
6  0.150762  0.074463  0.160106  0.092899  0.205718  0.112819   1.530643   
7  0.160514  0.076767  0.144337  0.110532  0.231962  0.121430   1.397156   
8  0.142239  0.078018  0.138587  0.088206  0.208587  0.120381   1.099746   
9  0.134329  0.080350  0.121451  0.075580  0.201957  0.126377   1.190368   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   
5     8.308895  0.963181  0.738307  ...  0.132786  0.110132  0.017112   
6     5.987498  0.967573  0.762638  ...  0.150762  0.105945  0.026230   
7     4.766611  0.959255  0.719858  ...  0.160514  0.093052  0.017758   
8     4.070284  0.970723  0.770992  ...  0.142239  0.096729  0.017957   
9     4.787310  0.975246  0.804505  ...  0.134329  0.105881  0.019300   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  
5  0.253968  0.298222  0.007812  2.726562  2.718750  0.125160   male  
6  0.266667  0.479620  0.007812  5.312500  5.304688  0.123992   male  
7  0.144144  0.301339  0.007812  0.539062  0.531250  0.283937   male  
8  0.250000  0.336476  0.007812  2.164062  2.156250  0.148272   male  
9  0.262295  0.340365  0.015625  4.695312  4.679688  0.089920   male  

[10 rows x 21 columns]

In [35]:
data.tail(10)

meanfreq        sd    median       Q25       Q75       IQR      skew  \
3158  0.183667  0.040607  0.182534  0.156480  0.207646  0.051166  2.054138   
3159  0.168794  0.085842  0.188980  0.095558  0.240229  0.144671  1.462248   
3160  0.151771  0.089147  0.185970  0.058159  0.230199  0.172040  1.227710   
3161  0.170656  0.081237  0.184277  0.113012  0.239096  0.126084  1.378256   
3162  0.146023  0.092525  0.183434  0.041747  0.224337  0.182590  1.384981   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859  1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193  0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936  1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435  1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756  1.705029   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
3158  7.483019  0.898138  0.313925  ...  0.183667  0.149237  0.018648   
3159  5.077956  0.956201  0.706861  ...  0.168794  0.182863  0.020699   
3160  4.304354  0.962045  0.744590  ...  0.151771  0.201600  0.023426   
3161  5.431663  0.950750  0.658558  ...  0.170656  0.198475  0.160000   
3162  5.118927  0.948999  0.659825  ...  0.146023  0.195640  0.039506   
3163  6.630383  0.962934  0.763182  ...  0.131884  0.182790  0.083770   
3164  2.503954  0.960716  0.709570  ...  0.116221  0.188980  0.034409   
3165  6.604509  0.946854  0.654196  ...  0.142056  0.209918  0.039506   
3166  5.388298  0.950436  0.675470  ...  0.143659  0.172375  0.034483   
3167  5.769115  0.938829  0.601529  ...  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx   label  
3158  0.262295  0.550312  0.007812  3.421875  3.414062  0.166503  female  
3159  0.271186  0.988281  0.007812  5.882812  5.875000  0.268617  female  
3160  0.266667  0.766741  0.007812  4.007812  4.000000  0.192220  female  
3161  0.253968  0.414062  0.007812  0.734375  0.726562  0.336918  female  
3162  0.275862  0.533854  0.007812  2.992188  2.984375  0.258924  female  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929  female  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897  female  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759  female  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002  female  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000  female  

[10 rows x 21 columns]

**Последний столбец датафрейма (label) считать меткой, все предыду щие (начиная с meanfreq и заканчивая modindx) – координатами вектора**

In [36]:
X = data.drop('label', axis=1)
y = data['label']

**Декодировать метки с помощью класса LabelEncoder, таким образом, вместо строк, метки должны быть заданы численно (0 или 1)**


In [41]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

In [51]:
print(y); print(y.max(), y.min());

[1 1 1 ... 0 0 0]
1 0


**Стандартизировать данные – X (класс StandardScaler)**

In [55]:
from sklearn.preprocessing import StandardScaler
# Создать стандартизатор
standardizer = StandardScaler()
# Стандартизировать признаки
features_stand = standardizer.fit_transform(X)

In [59]:
print(features_stand)

[[-4.04924806  0.4273553  -4.22490077 ... -1.43142165 -1.41913712
  -1.45477229]
 [-3.84105325  0.6116695  -3.99929342 ... -1.41810716 -1.4058184
  -1.01410294]
 [-3.46306647  1.60384791 -4.09585052 ... -1.42920257 -1.41691733
  -1.06534356]
 ...
 [-1.29877326  2.32272355 -0.05197279 ... -0.5992661  -0.58671739
   0.17588664]
 [-1.2452018   2.012196   -0.01772849 ... -0.41286326 -0.40025537
   1.14916112]
 [-0.51474626  2.14765111 -0.07087873 ... -1.27608595 -1.2637521
   1.47567886]]


**Разделить данные на обучающую (80%) и тестовую (20%) выборки (from sklearn.model_selection import train_test_split)**

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

**Обучить модель на базе класса SVC (kernel='linear', остальные настройки – по умолчанию)**

In [66]:
from sklearn.svm import SVC

svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)


SVC(kernel='linear')

In [68]:
y_pred = svclassifier.predict(X_test)

In [63]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[289  47]
 [ 10 288]]
              precision    recall  f1-score   support

           0       0.97      0.86      0.91       336
           1       0.86      0.97      0.91       298

    accuracy                           0.91       634
   macro avg       0.91      0.91      0.91       634
weighted avg       0.92      0.91      0.91       634



**Вычислить метрику accuracy_score (from sklearn import metrics)**

In [64]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred)) 
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))


Mean Absolute Error: 0.08990536277602523
Mean Squared Error: 0.08990536277602523
Root Mean Squared Error: 0.29984222980765274


**Сменить ядро на RBF (kernel='rbf'), переобучить модель на тех же данных, вычислить accuracy_score с новым ядром**

In [69]:
# Ядро Гаусса
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf') 
svclassifier.fit(X_train, y_train)


SVC()

In [70]:
y_pred = svclassifier.predict(X_test)

In [71]:
from sklearn.metrics import classification_report, confusion_matrix 
print(confusion_matrix(y_test, y_pred)) 
print(classification_report(y_test, y_pred))


[[187 149]
 [ 64 234]]
              precision    recall  f1-score   support

           0       0.75      0.56      0.64       336
           1       0.61      0.79      0.69       298

    accuracy                           0.66       634
   macro avg       0.68      0.67      0.66       634
weighted avg       0.68      0.66      0.66       634



In [72]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred)) 
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.3359621451104101
Mean Squared Error: 0.3359621451104101
Root Mean Squared Error: 0.5796224159833797
