In [27]:
import pandas as pd
import numpy as np

In [28]:
# Создать фрейм данных
df1 = pd.DataFrame({'z': np.random.randint(0, 2, 80)})
df1

z
0   1
1   0
2   1
3   0
4   0
.. ..
75  0
76  1
77  1
78  1
79  1

[80 rows x 1 columns]

In [1]:
from sklearn.neural_network import MLPClassifier

In [4]:
X = [[0., 0.], [1., 1.]]
y = [0, 1]

In [10]:
#MLP тренируется на двух массивах:массиве X размера (n_samples,n_features)
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=1)

In [13]:
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [14]:
#После подгонки (обучения)модель может предсказывать этикетки для новых образцов:
clf.predict([[2., 2.], [-1., -2.]])

array([1, 0])

In [16]:
#MLP может подогнать нелинейную модель к обучающим данным. clf.coefs_ содержит весовые матрицы
[coef.shape for coef in clf.coefs_]

[(2, 5), (5, 2), (2, 1)]

In [17]:
clf.predict_proba([[2., 2.], [1., 2.]])

array([[1.96718015e-04, 9.99803282e-01],
       [1.96718015e-04, 9.99803282e-01]])

In [19]:
X = [[0., 0.], [1., 1.]]
y = [[0, 1], [1, 1]]

In [20]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15,), random_state=1)

In [21]:
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(15,), random_state=1,
              solver='lbfgs')

In [22]:
clf.predict([[1., 2.]])

array([[1, 1]])

In [23]:
clf.predict([[0., 0.]])

array([[0, 1]])