In [109]:
import sklearn 
from sklearn import datasets
import numpy as np
from sklearn.datasets import load_files

In [110]:
path = 'C:\\ML\\Lesson_13\\docs.zip'

In [111]:
docs = sklearn.datasets.load_files('C:\ML\Lesson_13\docs')

In [112]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
bag = count.fit_transform(docs)
print(count.vocabulary_)
print(bag.toarray())

{'data': 0, 'filenames': 2, 'target_names': 4, 'target': 3, 'descr': 1}
[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]]


In [113]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer(ngram_range=(1, 2))
bag = count.fit_transform(docs)
print(count.vocabulary_)
print(bag.toarray())

{'data': 0, 'filenames': 2, 'target_names': 4, 'target': 3, 'descr': 1}
[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 1 0 0 0]]


In [114]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
vectorizer = CountVectorizer()
transformer = TfidfTransformer()
count = vectorizer.fit_transform(docs)
tfidf_matrix = transformer.fit_transform(count)
print(tfidf_matrix.toarray())

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]


In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer()
tfidf_matrix = tfidf_vec.fit_transform(docs)
print(tfidf_matrix.toarray())

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]]
