1. Реализуют все стандартные быстрые унарные математические операции

In [ ]:
import numpy as np

In [28]:
data = np.random.randint(10, 20, size = (2, 3))
print(data)

[[11 14 17]
 [13 13 11]]


In [35]:
print(data.mean());
print(data.sum());
print(data.mean(axis=1));
print(data.sum(axis=0));

13.166666666666666
79
[14.         12.33333333]
[24 27 28]


In [30]:
print(data.shape)

(2, 3)


 2. Преобразуют исходный двумерный массив в трехмерный

In [31]:
data2 = np.reshape(data, (3, 2))
print(data2)


[[11 14]
 [17 13]
 [13 11]]
